################################### Configuração de checagem, padrão de 1s ###########################

tempo.checagem: 2.0


################################### Configurações do Elasticsearch ###################################

# Setar de acordo com as configurações locais do ES.

index.es: "index"
doc.type.es: "doc_type"
last.check.es: "timestamp"